const quotes = [
    { name: "Aatrox", quote: "Fight! Or be forgotten!" },
    { name: "Aatrox", quote: "I am not your enemy, I am the enemy!" },
    { name: "Ahri", quote: "Don't you trust me?" },
    { name: "Amumu", quote: "I thought you'd never pick me." },
    { name: "Amumu", quote: "Okay..." },
    { name: "Ashe", quote: "All the world in one arrow." },
    { name: "Ashe", quote: "Check out these curves, I was talking about the bow." },
    { name: "Azir", quote: "The order is given!" },
    { name: "Brand", quote: "Ready to set the world on fire?" },
    { name: "Draven", quote: "Welcome to the League of Draven!" },
    { name: "Ekko", quote: "It's not how much time you have. It's how you use it." },
    { name: "Ekko", quote: "Patience, what’s that?" },
    { name: "Evelynn", quote: "You know you want me." },
    { name: "Fiddlesticks", quote: "FEAR!!!" },
    { name: "Fiddlesticks", quote: "I hear crows." },
    { name: "Fiddlesticks", quote: "Is someone there?" },
    { name: "Fiddlesticks", quote: "It moves around night!" },
    { name: "Fiddlesticks", quote: "Someone help! I can't find my way!" },
    { name: "Fiddlesticks", quote: "There's something in the field!" },
    { name: "Fizz", quote: "Let me at 'em!" },
    { name: "Heimerdinger", quote: "Hmm, not enough variables. Not nearly enough variable." },
    { name: "Heimerdinger", quote: "Indeed! A wise choice!" },
    { name: "Heimerdinger", quote: "The Q-sin of U-root, divided by...." },
    { name: "Heimerdinger", quote: "Wonderfully efficient!" },
    { name: "Jhin", quote: "One. Two. Three Four!" },
    { name: "Jhin", quote: "The ectasy of opening night." },
    { name: "Jinx", quote: "Rules are made to be broken. Like buildings! Or people!" },
    { name: "Jinx", quote: "Smile! It's called 'gun-PLAY'" },
    { name: "Kassadin", quote: "The balance of power must be preserved!" },
    { name: "Leblanc", quote: "The Black Rose shall bloom once more." },
    { name: "Lee Sin", quote: "Blindness is no impairment against a smelling the enemy." },
    { name: "Lee Sin", quote: "We do what we must!" },
    { name: "Lee Sin", quote: "Your will, My hands!" },
    { name: "Master Yi", quote: "Doubt is the greatest enemy." },
    { name: "Master Yi", quote: "Form before strength." },
    { name: "Master Yi", quote: "In me, Wuju lives on." },
    { name: "Master Yi", quote: "My blade, is yours." },
    { name: "Master Yi", quote: "The key to immortality, not dying." },
    { name: "Miss Fortune", quote: "Fortune doesn't favor fools." },
    { name: "Miss Fortune", quote: "Watch your mouth kid, or you'll find yourself respawning at home." },
    { name: "Nasus", quote: "The cycle of life and death continues. We will live. They will die." },
    { name: "Pantheon", quote: "I will remember your name, and shout it to the heavens!" },
    { name: "Pantheon", quote: "It's a privilege to die at my feet!" },
    { name: "Poppy", quote: "Me? The hero? Nah, that’s ridiculous!" },
    { name: "Rakan", quote: "R: Hey babe" },
    { name: "Rakan", quote: "Xayah: Yeah?" },
    { name: "Rakan", quote: "R: You hungry?" },
    { name: "Rammus", quote: "OK." },
    { name: "Rammus", quote: "Alright!" },
    { name: "Shaco", quote: "Why so serious?" },
    { name: "Sona", quote: "A surprise encore? If they insist." },
    { name: "Sona", quote: "Adagio, Summoner." },
    { name: "Sona", quote: "Only you can hear me summoner, what masterpiece shall we play today?" },
    { name: "Sona", quote: "Order through music." },
    { name: "Teemo", quote: "Another mushroom, another victim." },
    { name: "Teemo", quote: "Hut two, three, four!" },
    { name: "Teemo", quote: "Never underestimate the power of the scouts code." },
    { name: "Teemo", quote: "Size doesn't mean everything" },
    { name: "Thresh", quote: "Me, mad? Haha... quite likely." },
    { name: "Thresh", quote: "What delightful agony we shall inflict." },
    { name: "Tristana", quote: "Once a Vandal gunner, always a Vandal gunner." },
    { name: "Tristana", quote: "Who wants some? You want some?! Come on!" },
    { name: "Vayne", quote: "Let us hunt those who have fallen into darkness." },
    { name: "Vi", quote: "If you hit a wall, hit it hard." },
    { name: "Vi", quote: "Punch first. Ask questions while punching." },
    { name: "Vladimir", quote: "Go ahead, be negative! You'll be just my type!" },
    { name: "Xayah", quote: "I'll just be over here...sharpening my feathers" },
    { name: "Yasuo", quote: "Death is like the wind. Always by my side." },
    { name: "Zed", quote: "Embrace the shadow." },
    { name: "Zed", quote: "The truth lies in darkness." },
    { name: "Zed", quote: "The unseen blade is the deadliest." }
  ];
  
  module.exports = quotes;
  
  